### ISSUE TITLE
Go panic

### ISSUE THREAD

**Issue by alexbilbie** [mlabouardy/komiser#29]
I've downloaded the latest macOS build (as listed in the README) and I get a Go runtime panic:

```
2018/03/20 16:32:21 http: panic serving [::1]:55404: runtime error: invalid memory address or nil pointer dereference
goroutine 2142 [running]:
net/http.(*conn).serve.func1(0xc4204f9ea0)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x1dd3680, 0x2e70730)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/mlabouardy/komiser/services.AWS.getAutoScalingGroups(0xc4211f87b0, 0x9, 0x2de2520, 0xc42001ac60, 0x2dde220, 0xc4201926a0, 0xc420163200, 0xc42007a580, 0x2, 0x5, ...)
	/go/src/github.com/mlabouardy/komiser/services/autoscaling.go:40 +0x3ee
github.com/mlabouardy/komiser/services.AWS.DescribeAutoScalingGroups(0xc42000a26b, 0x9, 0x2de2520, 0xc42001ac60, 0x2dde220, 0xc4201926a0, 0xc420163200, 0xc42007a580, 0x2, 0x5, ...)
	/go/src/github.com/mlabouardy/komiser/services/autoscaling.go:16 +0x10c
github.com/mlabouardy/komiser/handlers.(*AWSHandler).AutoScalingGroupHandler(0xc4201981e0, 0x35a0078, 0xc422287ce0, 0xc4202a2f00)
	/go/src/github.com/mlabouardy/komiser/handlers/ec2_handler.go:29 +0xe6
github.com/mlabouardy/komiser/handlers.(*AWSHandler).AutoScalingGroupHandler-fm(0x35a0078, 0xc422287ce0, 0xc4202a2f00)
	/go/src/github.com/mlabouardy/komiser/main.go:43 +0x48
net/http.HandlerFunc.ServeHTTP(0xc420167580, 0x35a0078, 0xc422287ce0, 0xc4202a2f00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201690a0, 0x35a0078, 0xc422287ce0, 0xc4202a2f00)
	/go/src/github.com/gorilla/mux/mux.go:159 +0x101
github.com/gorilla/handlers.(*cors).ServeHTTP(0xc4201c4120, 0x35a0078, 0xc422287ce0, 0xc4202a2d00)
	/go/src/github.com/gorilla/handlers/cors.go:51 +0xa6f
github.com/gorilla/handlers.loggingHandler.ServeHTTP(0x2de1860, 0xc42000c018, 0x2de0ae0, 0xc4201c4120, 0x2de8aa0, 0xc4202c0540, 0xc4202a2d00)
	/go/src/github.com/gorilla/handlers/handlers.go:69 +0x121
github.com/gorilla/handlers.(*loggingHandler).ServeHTTP(0xc420193880, 0x2de8aa0, 0xc4202c0540, 0xc4202a2d00)
	<autogenerated>:8 +0x86
net/http.serverHandler.ServeHTTP(0xc420144dc0, 0x2de8aa0, 0xc4202c0540, 0xc4202a2d00)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4204f9ea0, 0x2de93e0, 0xc423d2a7c0)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
```

**Comment by mlabouardy** [comment]
have you tried the docker image ?
