### ISSUE TITLE
Request to /costs failing 

### ISSUE THREAD

**Issue by v2nek** [mlabouardy/komiser#40]
Hi there, thanks for nice tool

when i run it, i get this on /costs request:

```
172.18.0.3 - - [29/Mar/2018:09:34:45 +0000] "GET /cost HTTP/1.1" 500 41
2018/03/29 09:34:49 http: panic serving 172.18.0.3:37096: runtime error: invalid memory address or nil pointer dereference
goroutine 677 [running]:
net/http.(*conn).serve.func1(0xc420a8abe0)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x11c9fa0, 0x225f590)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/mlabouardy/komiser/services.AWS.getAutoScalingGroups(0xc420aaa190, 0xe, 0x21d1460, 0xc420010c00, 0x21cd460, 0xc420174440, 0xc420146f30, 0xc420056600, 0x2, 0x5, ...)
	/go/src/github.com/mlabouardy/komiser/services/autoscaling.go:40 +0x3ee
github.com/mlabouardy/komiser/services.AWS.DescribeAutoScalingGroups(0xc42000c073, 0x9, 0x21d1460, 0xc420010c00, 0x21cd460, 0xc420174440, 0xc420146f30, 0xc420056600, 0x2, 0x5, ...)
	/go/src/github.com/mlabouardy/komiser/services/autoscaling.go:16 +0x10c
github.com/mlabouardy/komiser/handlers.(*AWSHandler).AutoScalingGroupHandler(0xc4201761e0, 0x7f5535192378, 0xc420abbc20, 0xc42018e500)
	/go/src/github.com/mlabouardy/komiser/handlers/ec2_handler.go:29 +0xe6
github.com/mlabouardy/komiser/handlers.(*AWSHandler).AutoScalingGroupHandler-fm(0x7f5535192378, 0xc420abbc20, 0xc42018e500)
	/go/src/github.com/mlabouardy/komiser/main.go:43 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4200e7250, 0x7f5535192378, 0xc420abbc20, 0xc42018e500)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc42014ad20, 0x7f5535192378, 0xc420abbc20, 0xc42018e500)
	/go/src/github.com/gorilla/mux/mux.go:159 +0x101
github.com/gorilla/handlers.(*cors).ServeHTTP(0xc42012def0, 0x7f5535192378, 0xc420abbc20, 0xc42018e100)
	/go/src/github.com/gorilla/handlers/cors.go:51 +0xa6f
github.com/gorilla/handlers.loggingHandler.ServeHTTP(0x21d0a60, 0xc42000e018, 0x21cfd20, 0xc42012def0, 0x21d7960, 0xc420300620, 0xc42018e100)
	/go/src/github.com/gorilla/handlers/handlers.go:69 +0x121
github.com/gorilla/handlers.(*loggingHandler).ServeHTTP(0xc420175620, 0x21d7960, 0xc420300620, 0xc42018e100)
	<autogenerated>:8 +0x86
net/http.serverHandler.ServeHTTP(0xc42012ee70, 0x21d7960, 0xc420300620, 0xc42018e100)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420a8abe0, 0x21d82a0, 0xc420acb880)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
```

This happens on multiple non-related accounts, so problem seems to be in code.
Using :latest from docker hub.

**Comment by mlabouardy** [comment]
its related to https://github.com/mlabouardy/komiser/issues/37 it will be fixed in the upcoming release

**Comment by BrandonShutter** [comment]
When is the upcoming release?

**Comment by mlabouardy** [comment]
@BrandonShutter @v2nek fixed https://github.com/mlabouardy/komiser/pull/47
