### ISSUE TITLE
`http: panic serving [::1]:64735: runtime error: invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by davidjeddy** [mlabouardy/komiser#45]
**Process:**
wget https://s3.us-east-1.amazonaws.com/komiser/1.0.0/osx/komiser
chmod +X komiser
sudo ./komiser start --port 3000 --duration 30

Visit `http://localhost:3000` in browser

**Results:**
```BASH
::1 - - [03/Apr/2018:10:50:24 -0400] "GET / HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /styles.05d4aeeb77605b05dbf9.bundle.css HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /inline.47d04ba836b188db631f.bundle.js HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /polyfills.abdf53ca655716e505e0.bundle.js HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /main.8097dd79d6203e629625.bundle.js HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /vpc HTTP/1.1" 200 2
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /acl HTTP/1.1" 200 2
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /security_group HTTP/1.1" 200 3
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /nat HTTP/1.1" 200 1
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /internet_gateway HTTP/1.1" 200 2
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /eip HTTP/1.1" 200 2
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /key_pair HTTP/1.1" 200 2
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /route_table HTTP/1.1" 200 2
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /dynamodb HTTP/1.1" 200 66
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /ebs HTTP/1.1" 200 81
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /cost HTTP/1.1" 200 707
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /snapshot HTTP/1.1" 200 27
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /lambda HTTP/1.1" 200 90
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /elb HTTP/1.1" 200 32
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /sqs HTTP/1.1" 200 3
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /sns HTTP/1.1" 200 2
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /hosted_zone HTTP/1.1" 200 2
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /cloudwatch HTTP/1.1" 200 42
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /iam/role HTTP/1.1" 200 3
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /iam/group HTTP/1.1" 200 2
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /iam/policy HTTP/1.1" 200 3
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /iam/user HTTP/1.1" 200 2
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /cloudfront HTTP/1.1" 200 2
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /s3 HTTP/1.1" 200 3
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /ec2 HTTP/1.1" 200 568
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/s3.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/snapshot.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/logo.svg HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/snapshot_size.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/user.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/ebs.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/role.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/group.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/policy.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/distribution.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/vpc.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/acl.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/sg.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/nat.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/igw.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/eip.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/keypair.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/asg.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/route_table.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/cluster.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/service.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/task.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/rds.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/dynamodb.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/dynamodb_write.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/dynamodb_read.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/sqs.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/sns.png HTTP/1.1" 304 0
::1 - - [03/Apr/2018:10:50:25 -0400] "GET /assets/images/hostedzone.png HTTP/1.1" 304 0
2018/04/03 10:50:48 http: panic serving [::1]:64730: runtime error: invalid memory address or nil pointer dereference
goroutine 2254 [running]:
net/http.(*conn).serve.func1(0xc4204fac80)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x1dd3740, 0x2e70730)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/mlabouardy/komiser/services.AWS.getAutoScalingGroups(0xc420359df0, 0x9, 0x2de2520, 0xc42000ed20, 0x2dde220, 0xc420184580, 0xc4201591d0, 0xc42006a580, 0x2, 0x5, ...)
	/go/src/github.com/mlabouardy/komiser/services/autoscaling.go:40 +0x3ee
github.com/mlabouardy/komiser/services.AWS.DescribeAutoScalingGroups(0xc42015c931, 0x9, 0x2de2520, 0xc42000ed20, 0x2dde220, 0xc420184580, 0xc4201591d0, 0xc42006a580, 0x2, 0x5, ...)
	/go/src/github.com/mlabouardy/komiser/services/autoscaling.go:16 +0x10c
github.com/mlabouardy/komiser/handlers.(*AWSHandler).AutoScalingGroupHandler(0xc42018c1e0, 0x35a0078, 0xc420dd6ba0, 0xc420bd7a00)
	/go/src/github.com/mlabouardy/komiser/handlers/ec2_handler.go:29 +0xe6
github.com/mlabouardy/komiser/handlers.(*AWSHandler).AutoScalingGroupHandler-fm(0x35a0078, 0xc420dd6ba0, 0xc420bd7a00)
	/go/src/github.com/mlabouardy/komiser/main.go:43 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42015d6a0, 0x35a0078, 0xc420dd6ba0, 0xc420bd7a00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc42015f730, 0x35a0078, 0xc420dd6ba0, 0xc420bd7a00)
	/go/src/github.com/gorilla/mux/mux.go:159 +0x101
github.com/gorilla/handlers.(*cors).ServeHTTP(0xc4201ca090, 0x35a0078, 0xc420dd6ba0, 0xc420bd7500)
	/go/src/github.com/gorilla/handlers/cors.go:51 +0xa6f
github.com/gorilla/handlers.loggingHandler.ServeHTTP(0x2de1860, 0xc42000c018, 0x2de0ae0, 0xc4201ca090, 0x2de8aa0, 0xc420401180, 0xc420bd7500)
	/go/src/github.com/gorilla/handlers/handlers.go:69 +0x121
github.com/gorilla/handlers.(*loggingHandler).ServeHTTP(0xc420185780, 0x2de8aa0, 0xc420401180, 0xc420bd7500)
	<autogenerated>:8 +0x86
net/http.serverHandler.ServeHTTP(0xc42013cfd0, 0x2de8aa0, 0xc420401180, 0xc420bd7500)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4204fac80, 0x2de93e0, 0xc420506000)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
2018/04/03 10:51:09 http: panic serving [::1]:64734: runtime error: invalid memory address or nil pointer dereference
goroutine 2434 [running]:
net/http.(*conn).serve.func1(0xc4204fcfa0)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x1dd3740, 0x2e70730)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/mlabouardy/komiser/services.AWS.getAutoScalingGroups(0xc42088ec10, 0x9, 0x2de2520, 0xc42000ed20, 0x2dde220, 0xc420184580, 0xc4201591d0, 0xc42006a580, 0x2, 0x5, ...)
	/go/src/github.com/mlabouardy/komiser/services/autoscaling.go:40 +0x3ee
github.com/mlabouardy/komiser/services.AWS.DescribeAutoScalingGroups(0xc42015c931, 0x9, 0x2de2520, 0xc42000ed20, 0x2dde220, 0xc420184580, 0xc4201591d0, 0xc42006a580, 0x2, 0x5, ...)
	/go/src/github.com/mlabouardy/komiser/services/autoscaling.go:16 +0x10c
github.com/mlabouardy/komiser/handlers.(*AWSHandler).AutoScalingGroupHandler(0xc42018c1e0, 0x35a0078, 0xc420254510, 0xc420bd6800)
	/go/src/github.com/mlabouardy/komiser/handlers/ec2_handler.go:29 +0xe6
github.com/mlabouardy/komiser/handlers.(*AWSHandler).AutoScalingGroupHandler-fm(0x35a0078, 0xc420254510, 0xc420bd6800)
	/go/src/github.com/mlabouardy/komiser/main.go:43 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42015d6a0, 0x35a0078, 0xc420254510, 0xc420bd6800)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc42015f730, 0x35a0078, 0xc420254510, 0xc420bd6800)
	/go/src/github.com/gorilla/mux/mux.go:159 +0x101
github.com/gorilla/handlers.(*cors).ServeHTTP(0xc4201ca090, 0x35a0078, 0xc420254510, 0xc4200f4600)
	/go/src/github.com/gorilla/handlers/cors.go:51 +0xa6f
github.com/gorilla/handlers.loggingHandler.ServeHTTP(0x2de1860, 0xc42000c018, 0x2de0ae0, 0xc4201ca090, 0x2de8aa0, 0xc4202d02a0, 0xc4200f4600)
	/go/src/github.com/gorilla/handlers/handlers.go:69 +0x121
github.com/gorilla/handlers.(*loggingHandler).ServeHTTP(0xc420185780, 0x2de8aa0, 0xc4202d02a0, 0xc4200f4600)
	<autogenerated>:8 +0x86
net/http.serverHandler.ServeHTTP(0xc42013cfd0, 0x2de8aa0, 0xc4202d02a0, 0xc4200f4600)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4204fcfa0, 0x2de93e0, 0xc420506280)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
2018/04/03 10:51:22 http: panic serving [::1]:64731: runtime error: invalid memory address or nil pointer dereference
goroutine 2255 [running]:
net/http.(*conn).serve.func1(0xc4204fad20)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x1dd3740, 0x2e70730)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/mlabouardy/komiser/services.AWS.getAutoScalingGroups(0xc420646340, 0x9, 0x2de2520, 0xc42000ed20, 0x2dde220, 0xc420184580, 0xc4201591d0, 0xc42006a580, 0x2, 0x5, ...)
	/go/src/github.com/mlabouardy/komiser/services/autoscaling.go:40 +0x3ee
github.com/mlabouardy/komiser/services.AWS.DescribeAutoScalingGroups(0xc42015c931, 0x9, 0x2de2520, 0xc42000ed20, 0x2dde220, 0xc420184580, 0xc4201591d0, 0xc42006a580, 0x2, 0x5, ...)
	/go/src/github.com/mlabouardy/komiser/services/autoscaling.go:16 +0x10c
github.com/mlabouardy/komiser/handlers.(*AWSHandler).AutoScalingGroupHandler(0xc42018c1e0, 0x35a0078, 0xc420786c60, 0xc42025ce00)
	/go/src/github.com/mlabouardy/komiser/handlers/ec2_handler.go:29 +0xe6
github.com/mlabouardy/komiser/handlers.(*AWSHandler).AutoScalingGroupHandler-fm(0x35a0078, 0xc420786c60, 0xc42025ce00)
	/go/src/github.com/mlabouardy/komiser/main.go:43 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42015d6a0, 0x35a0078, 0xc420786c60, 0xc42025ce00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc42015f730, 0x35a0078, 0xc420786c60, 0xc42025ce00)
	/go/src/github.com/gorilla/mux/mux.go:159 +0x101
github.com/gorilla/handlers.(*cors).ServeHTTP(0xc4201ca090, 0x35a0078, 0xc420786c60, 0xc420bd7f00)
	/go/src/github.com/gorilla/handlers/cors.go:51 +0xa6f
github.com/gorilla/handlers.loggingHandler.ServeHTTP(0x2de1860, 0xc42000c018, 0x2de0ae0, 0xc4201ca090, 0x2de8aa0, 0xc4202d0fc0, 0xc420bd7f00)
	/go/src/github.com/gorilla/handlers/handlers.go:69 +0x121
github.com/gorilla/handlers.(*loggingHandler).ServeHTTP(0xc420185780, 0x2de8aa0, 0xc4202d0fc0, 0xc420bd7f00)
	<autogenerated>:8 +0x86
net/http.serverHandler.ServeHTTP(0xc42013cfd0, 0x2de8aa0, 0xc4202d0fc0, 0xc420bd7f00)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4204fad20, 0x2de93e0, 0xc420788100)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
2018/04/03 10:51:34 http: panic serving [::1]:64732: runtime error: invalid memory address or nil pointer dereference
goroutine 2470 [running]:
net/http.(*conn).serve.func1(0xc4201ce000)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x1dd3740, 0x2e70730)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/mlabouardy/komiser/services.AWS.getAutoScalingGroups(0xc4203f0650, 0x9, 0x2de2520, 0xc42000ed20, 0x2dde220, 0xc420184580, 0xc4201591d0, 0xc42006a580, 0x2, 0x5, ...)
	/go/src/github.com/mlabouardy/komiser/services/autoscaling.go:40 +0x3ee
github.com/mlabouardy/komiser/services.AWS.DescribeAutoScalingGroups(0xc42015c931, 0x9, 0x2de2520, 0xc42000ed20, 0x2dde220, 0xc420184580, 0xc4201591d0, 0xc42006a580, 0x2, 0x5, ...)
	/go/src/github.com/mlabouardy/komiser/services/autoscaling.go:16 +0x10c
github.com/mlabouardy/komiser/handlers.(*AWSHandler).AutoScalingGroupHandler(0xc42018c1e0, 0x35a0078, 0xc4214493e0, 0xc4200c6a00)
	/go/src/github.com/mlabouardy/komiser/handlers/ec2_handler.go:29 +0xe6
github.com/mlabouardy/komiser/handlers.(*AWSHandler).AutoScalingGroupHandler-fm(0x35a0078, 0xc4214493e0, 0xc4200c6a00)
	/go/src/github.com/mlabouardy/komiser/main.go:43 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42015d6a0, 0x35a0078, 0xc4214493e0, 0xc4200c6a00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc42015f730, 0x35a0078, 0xc4214493e0, 0xc4200c6a00)
	/go/src/github.com/gorilla/mux/mux.go:159 +0x101
github.com/gorilla/handlers.(*cors).ServeHTTP(0xc4201ca090, 0x35a0078, 0xc4214493e0, 0xc4200c7200)
	/go/src/github.com/gorilla/handlers/cors.go:51 +0xa6f
github.com/gorilla/handlers.loggingHandler.ServeHTTP(0x2de1860, 0xc42000c018, 0x2de0ae0, 0xc4201ca090, 0x2de8aa0, 0xc4204100e0, 0xc4200c7200)
	/go/src/github.com/gorilla/handlers/handlers.go:69 +0x121
github.com/gorilla/handlers.(*loggingHandler).ServeHTTP(0xc420185780, 0x2de8aa0, 0xc4204100e0, 0xc4200c7200)
	<autogenerated>:8 +0x86
net/http.serverHandler.ServeHTTP(0xc42013cfd0, 0x2de8aa0, 0xc4204100e0, 0xc4200c7200)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4201ce000, 0x2de93e0, 0xc420506100)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
2018/04/03 10:51:54 http: panic serving [::1]:64735: runtime error: invalid memory address or nil pointer dereference
goroutine 2472 [running]:
net/http.(*conn).serve.func1(0xc4201ce140)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x1dd3740, 0x2e70730)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/mlabouardy/komiser/services.AWS.getAutoScalingGroups(0xc4209f0cd0, 0x9, 0x2de2520, 0xc42000ed20, 0x2dde220, 0xc420184580, 0xc4201591d0, 0xc42006a580, 0x2, 0x5, ...)
	/go/src/github.com/mlabouardy/komiser/services/autoscaling.go:40 +0x3ee
github.com/mlabouardy/komiser/services.AWS.DescribeAutoScalingGroups(0xc42015c931, 0x9, 0x2de2520, 0xc42000ed20, 0x2dde220, 0xc420184580, 0xc4201591d0, 0xc42006a580, 0x2, 0x5, ...)
	/go/src/github.com/mlabouardy/komiser/services/autoscaling.go:16 +0x10c
github.com/mlabouardy/komiser/handlers.(*AWSHandler).AutoScalingGroupHandler(0xc42018c1e0, 0x35a0078, 0xc420243050, 0xc4200c6b00)
	/go/src/github.com/mlabouardy/komiser/handlers/ec2_handler.go:29 +0xe6
github.com/mlabouardy/komiser/handlers.(*AWSHandler).AutoScalingGroupHandler-fm(0x35a0078, 0xc420243050, 0xc4200c6b00)
	/go/src/github.com/mlabouardy/komiser/main.go:43 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42015d6a0, 0x35a0078, 0xc420243050, 0xc4200c6b00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc42015f730, 0x35a0078, 0xc420243050, 0xc4200c6b00)
	/go/src/github.com/gorilla/mux/mux.go:159 +0x101
github.com/gorilla/handlers.(*cors).ServeHTTP(0xc4201ca090, 0x35a0078, 0xc420243050, 0xc4200f4200)
	/go/src/github.com/gorilla/handlers/cors.go:51 +0xa6f
github.com/gorilla/handlers.loggingHandler.ServeHTTP(0x2de1860, 0xc42000c018, 0x2de0ae0, 0xc4201ca090, 0x2de8aa0, 0xc420249ce0, 0xc4200f4200)
	/go/src/github.com/gorilla/handlers/handlers.go:69 +0x121
github.com/gorilla/handlers.(*loggingHandler).ServeHTTP(0xc420185780, 0x2de8aa0, 0xc420249ce0, 0xc4200f4200)
	<autogenerated>:8 +0x86
net/http.serverHandler.ServeHTTP(0xc42013cfd0, 0x2de8aa0, 0xc420249ce0, 0xc4200f4200)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4201ce140, 0x2de93e0, 0xc420c2a280)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
```

**Environment:**
OSX 10.13.3
Go 1.10
Docker 18.03.0-ce

**Comment by mlabouardy** [comment]
related to https://github.com/mlabouardy/komiser/issues/41

will be fixed in upcoming release

**Comment by mlabouardy** [comment]
@davidjeddy fixed https://github.com/mlabouardy/komiser/pull/47
