### ISSUE TITLE
Resources reported as 'missing'

### ISSUE THREAD

**Issue by spynode** [mlabouardy/komiser#77]
While most of functionality is available, with IAM permission set provided in https://raw.githubusercontent.com/mlabouardy/komiser/master/policy.json, Komiser (2.1.0) is reporting several resources as missing.

```
support:DescribeCases is missing
cloudwatchlogs:DescribeLogGroups is missing
cloudwatch:GetMetricStatistics is missing
apigateway:GET is missing

```
There is following exception showing up in logs:
```
10.2.6.12 - - [14/May/2019:10:57:57 +0000] "GET / HTTP/1.1" 200 2856
2019/05/14 10:57:57 http: panic serving 172.30.87.165:48326: runtime error: invalid memory address or nil pointer dereference
goroutine 245 [running]:
net/http.(*conn).serve.func1(0xc420952460)
	/usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0x1e62be0, 0x44268a0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/mlabouardy/komiser/services/aws.AWS.DescribeIAMUser(0xc4203fcff0, 0xc, 0x2570100, 0xc4200f5260, 0x256d000, 0xc420402160, 0xc4202f69f0, 0xc4201a2200, 0x2, 0x5, ...)
	/go/src/github.com/mlabouardy/komiser/services/aws/iam.go:49 +0x203
github.com/mlabouardy/komiser/handlers/aws.(*AWSHandler).IAMUserHandler(0xc4202963c0, 0x7f1071d47318, 0xc4209ff4a0, 0xc42001c900)
	/go/src/github.com/mlabouardy/komiser/handlers/aws/iam_handler.go:72 +0xf9
github.com/mlabouardy/komiser/handlers/aws.(*AWSHandler).IAMUserHandler-fm(0x7f1071d47318, 0xc4209ff4a0, 0xc42001c900)
	/go/src/github.com/mlabouardy/komiser/main.go:37 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4203b8860, 0x7f1071d47318, 0xc4209ff4a0, 0xc42001c900)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/mlabouardy/komiser/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4203bf110, 0x7f1071d47318, 0xc4209ff4a0, 0xc42001c900)
	/go/src/github.com/mlabouardy/komiser/vendor/github.com/gorilla/mux/mux.go:162 +0xed
github.com/mlabouardy/komiser/vendor/github.com/gorilla/handlers.(*cors).ServeHTTP(0xc4204aac60, 0x7f1071d47318, 0xc4209ff4a0, 0xc42001c600)
	/go/src/github.com/mlabouardy/komiser/vendor/github.com/gorilla/handlers/cors.go:51 +0xa2e
github.com/mlabouardy/komiser/vendor/github.com/gorilla/handlers.loggingHandler.ServeHTTP(0x256fac0, 0xc42000e018, 0x256eec0, 0xc4204aac60, 0x2578ea0, 0xc42048a0e0, 0xc42001c600)
	/go/src/github.com/mlabouardy/komiser/vendor/github.com/gorilla/handlers/handlers.go:69 +0x123
net/http.serverHandler.ServeHTTP(0xc42025ed00, 0x2578ea0, 0xc42048a0e0, 0xc42001c600)
	/usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420952460, 0x25798a0, 0xc420558b00)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b

```
but I think this is unrelated and is consequence of k8s health check simply pointing GET to /

Most of these requests are logged simply as:
```
172.30.119.34 - - [15/May/2019:12:44:02 +0000] "GET /aws/vpc/subnets HTTP/1.1" 500 42
172.30.119.34 - - [15/May/2019:12:43:50 +0000] "GET /aws/apigateway/apis HTTP/1.1" 500 37
```

Applied IAM policy matches the one from docs:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "1",
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeRegions",
                "ec2:DescribeInstances",
                "ec2:DescribeVolumes",
                "ec2:DescribeVpcs",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeNatGateways",
                "ec2:DescribeRouteTables",
                "ec2:DescribeSnapshots",
                "ec2:DescribeNetworkAcls",
                "ec2:DescribeKeyPairs",
                "ec2:DescribeInternetGateways"
            ],
            "Resource": "*"
        },
        {
            "Sid": "2",
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeAddresses",
                "ec2:DescribeSnapshots",
                "elasticloadbalancing:DescribeLoadBalancers",
                "autoscaling:DescribeAutoScalingGroups",
                "ce:GetCostAndUsage",
                "s3:ListAllMyBuckets"
            ],
            "Resource": "*"
        },
        {
            "Sid": "3",
            "Effect": "Allow",
            "Action": [
                "lambda:ListFunctions",
                "dynamodb:ListTables",
                "dynamodb:DescribeTable",
                "rds:DescribeDBInstances",
                "cloudwatch:DescribeAlarms",
                "cloudfront:ListDistributions",
                "ecs:DescribeClusters",
                "ecs:DescribeServices",
                "ecs:DescribeTasks"
            ],
            "Resource": "*"
        },
        {
            "Sid": "4",
            "Effect": "Allow",
            "Action": [
                "sqs:ListQueues",
                "route53:ListHostedZones",
                "sns:ListTopics",
                "iam:ListGroups",
                "iam:ListRoles",
                "iam:ListPolicies",
                "iam:ListUsers"
            ],
            "Resource": "*"
        },
        {
            "Sid": "5",
            "Effect": "Allow",
            "Action": [
                "acm:ListCertificates",
                "mq:ListBrokers",
                "cloudwatch:GetMetricStatistics",
                "cloudtrail:LookupEvents",
                "ce:GetCostAndUsage",
                "ce:GetCostForecast",
                "datapipeline:ListPipelines",
                "ec2:DescribeReservedInstances",
                "ec2:DescribeSpotFleetRequests",
                "ec2:DescribeScheduledInstances",
                "eks:ListClusters",
                "elasticache:DescribeCacheClusters",
                "es:ListDomainNames"
            ],
            "Resource": "*"
        },
        {
            "Sid": "6",
            "Effect": "Allow",
            "Action": [
                "glue:GetCrawlers",
                "glue:GetJobs",
                "organizations:DescribeOrganization",
                "iam:GetUser",
                "kinesis:ListStreams",
                "kinesis:ListShards",
                "kms:ListKeys",
                "redshift:DescribeClusters",
                "tag:GetResources",
                "route53:ListResourceRecordSets",
                "s3:ListAllMyBuckets",
                "support:DescribeCases",
                "support:DescribeTrustedAdvisorChecks",
                "swf:ListDomains"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by mlabouardy** [comment]
@spynode thanks for reporting this out

I'm trying to reproduce this locally, meanwhile can you add "cloudwatchlogs:DescribeLogGroups" permission to the IAM policy (I forgot to add it) :)

**Comment by mlabouardy** [comment]
"apigateway:GET" and ""cloudwatchlogs:DescribeLogGroups" are missing, I have updated the IAM policy

**Comment by mlabouardy** [comment]
@spynode adding the permissions below, should normally fix the issue :)
