### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by stepri** [mlabouardy/komiser#83]
```
komiser_1  | 2019/05/17 10:57:25 http: panic serving 172.19.0.1:33872: runtime error: invalid memory address or nil pointer dereference
komiser_1  | goroutine 192 [running]:
komiser_1  | net/http.(*conn).serve.func1(0xc4203d4f00)
komiser_1  | 	/usr/local/go/src/net/http/server.go:1726 +0xd0
komiser_1  | panic(0x1e62be0, 0x44268a0)
komiser_1  | 	/usr/local/go/src/runtime/panic.go:502 +0x229
komiser_1  | github.com/mlabouardy/komiser/services/aws.AWS.DescribeIAMUser(0x0, 0x0, 0x2570100, 0xc420140f00, 0x256d000, 0xc420396180, 0xc4203289c0, 0xc420156200, 0x2, 0x5, ...)
komiser_1  | 	/go/src/github.com/mlabouardy/komiser/services/aws/iam.go:49 +0x203
komiser_1  | github.com/mlabouardy/komiser/handlers/aws.(*AWSHandler).IAMUserHandler(0xc4202403c0, 0x7fc389e1be30, 0xc4200daae0, 0xc4200d3d00)
komiser_1  | 	/go/src/github.com/mlabouardy/komiser/handlers/aws/iam_handler.go:72 +0xf9
komiser_1  | github.com/mlabouardy/komiser/handlers/aws.(*AWSHandler).IAMUserHandler-fm(0x7fc389e1be30, 0xc4200daae0, 0xc4200d3d00)
komiser_1  | 	/go/src/github.com/mlabouardy/komiser/main.go:37 +0x48
komiser_1  | net/http.HandlerFunc.ServeHTTP(0xc420362860, 0x7fc389e1be30, 0xc4200daae0, 0xc4200d3d00)
komiser_1  | 	/usr/local/go/src/net/http/server.go:1947 +0x44
komiser_1  | github.com/mlabouardy/komiser/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4203670a0, 0x7fc389e1be30, 0xc4200daae0, 0xc4200d3d00)
komiser_1  | 	/go/src/github.com/mlabouardy/komiser/vendor/github.com/gorilla/mux/mux.go:162 +0xed
komiser_1  | github.com/mlabouardy/komiser/vendor/github.com/gorilla/handlers.(*cors).ServeHTTP(0xc42044cc60, 0x7fc389e1be30, 0xc4200daae0, 0xc4200d3b00)
komiser_1  | 	/go/src/github.com/mlabouardy/komiser/vendor/github.com/gorilla/handlers/cors.go:51 +0xa2e
komiser_1  | github.com/mlabouardy/komiser/vendor/github.com/gorilla/handlers.loggingHandler.ServeHTTP(0x256fac0, 0xc4200b2008, 0x256eec0, 0xc42044cc60, 0x2578ea0, 0xc420581dc0, 0xc4200d3b00)
komiser_1  | 	/go/src/github.com/mlabouardy/komiser/vendor/github.com/gorilla/handlers/handlers.go:69 +0x123
komiser_1  | net/http.serverHandler.ServeHTTP(0xc420209380, 0x2578ea0, 0xc420581dc0, 0xc4200d3b00)
komiser_1  | 	/usr/local/go/src/net/http/server.go:2694 +0xbc
komiser_1  | net/http.(*conn).serve(0xc4203d4f00, 0x25798a0, 0xc4202c0440)
komiser_1  | 	/usr/local/go/src/net/http/server.go:1830 +0x651
komiser_1  | created by net/http.(*Server).Serve
komiser_1  | 	/usr/local/go/src/net/http/server.go:2795 +0x27b
```

**Comment by mlabouardy** [comment]
@stepri can you give more details please

are you using the docker image or cli ?
what does the navigation icon say ? any missing permissions
